# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=20)),
                ('mname', models.TextField(max_length=20)),
                ('lname', models.TextField(max_length=20)),
                ('phone_mobile', models.CharField(max_length=15)),
                ('phone_fixed', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('Remarks', models.TextField()),
            ],
        ),
    ]
