# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callmgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apex_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='apex',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='callmgr.Apex'),
            preserve_default=False,
        ),
    ]
