# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callmgr', '0002_auto_20160108_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
