# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmgr', '0003_auto_20160108_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mname',
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apex',
            name='apex_name',
            field=models.CharField(max_length=100),
        ),
    ]
